site_name: Cookiecutter Data Science
site_description: A project template and directory structure for Python data science projects.
site_favicon: favicon.ico
repo_url: https://github.com/cristian-rincon/py-cookiecutter-datascience
edit_uri: edit/master/docs/docs
copyright: Project maintained by <a target=_blanks href="https://github.com/cristian-rincon">Cristian Rincón</a>.
theme: cinder
extra_css:
  - css/extra.css
pages:
  - Home: index.md
